# Generated by Django 5.2.4 on 2025-08-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0002_alter_clientcontract_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
