# Generated by Django 5.2.4 on 2025-08-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0003_phase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmilestone',
            name='billed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
