# Generated by Django 5.2.4 on 2025-08-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0004_billingmilestone_billed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingmilestone',
            old_name='expected_date',
            new_name='completed_date',
        ),
        migrations.RenameField(
            model_name='phase',
            old_name='date',
            new_name='revenue_date',
        ),
    ]
