# Generated by Django 5.2.4 on 2025-08-02 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0005_rename_expected_date_billingmilestone_completed_date_and_more'),
        ('integrations', '0002_crmclient_company_crmclient_is_receivable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_close', models.DateField()),
                ('stage', models.CharField(max_length=50)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.clientcontract')),
                ('crm_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.crmclient')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.deal')),
            ],
        ),
    ]
