# Generated by Django 5.2.4 on 2025-08-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0006_deal_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
