# Generated by Django 5.2.4 on 2025-08-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0007_alter_clientcontract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.deal'),
        ),
    ]
