# Generated by Django 5.2.4 on 2025-08-02 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0009_alter_commission_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_set', to='accounting_app.clientcontract'),
        ),
    ]
