# Generated by Django 5.2.4 on 2025-08-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0011_alter_deal_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.clientcontract'),
        ),
    ]
