# Generated by Django 5.2.4 on 2025-08-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0012_alter_deal_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.deal'),
        ),
    ]
