# Generated by Django 5.2.4 on 2025-08-03 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0013_invoice_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contract',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.clientcontract'),
        ),
    ]
