# Generated by Django 5.2.4 on 2025-08-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0014_alter_deal_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_gateway',
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('manual', 'Manual')], default='razorpay', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.invoice'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='quotes/')),
                ('notes', models.TextField(blank=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.deal')),
            ],
        ),
    ]
