# Generated by Django 5.2.4 on 2025-08-03 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0015_rename_payment_date_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.client'),
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.CharField(default='Quote for Deal', max_length=255),
        ),
    ]
