# Generated by Django 5.2.4 on 2025-08-03 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0016_quote_amount_quote_client_quote_status_quote_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
