# Generated by Django 5.2.4 on 2025-08-03 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0017_payment_paid_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
