# Generated by Django 5.2.4 on 2025-08-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0018_alter_quote_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='razopay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
