# Generated by Django 5.2.4 on 2025-08-04 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0020_commission_razorpay_order_id_quote_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.deal'),
        ),
    ]
