# Generated by Django 5.2.4 on 2025-08-04 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0021_alter_quote_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='accounting_app.deal'),
        ),
    ]
