# Generated by Django 5.2.4 on 2025-08-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0022_alter_quote_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
