# Generated by Django 5.2.4 on 2025-08-04 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0023_quote_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting_app.deal'),
        ),
    ]
