# Generated by Django 5.2.4 on 2025-08-05 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0027_vendorpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('credit', 'Credit')], default='bank_transfer', max_length=50)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_app.vendor')),
            ],
            options={
                'verbose_name': 'Vendor Payment',
                'verbose_name_plural': 'Vendor Payments',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='VendorPayment',
        ),
    ]
