# Generated by Django 5.2.4 on 2025-08-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0029_vendorpayment_delete_vendorpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
