# Generated by Django 5.2.4 on 2025-08-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0030_vendorbill_is_paid_vendorbill_paid_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='ack_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='eway_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='irn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
