# Generated by Django 5.2.4 on 2025-08-05 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0031_vendorbill_ack_no_vendorbill_eway_bill_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.invoice'),
        ),
        migrations.AddField(
            model_name='einvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='invoice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.invoice'),
        ),
        migrations.AddField(
            model_name='ewaybill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gstr1',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.client'),
        ),
        migrations.AddField(
            model_name='gstr1',
            name='invoices',
            field=models.ManyToManyField(blank=True, to='accounting_app.invoice'),
        ),
        migrations.AddField(
            model_name='gstr1',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gstr3b',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.client'),
        ),
        migrations.AddField(
            model_name='gstr3b',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gstr9',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.client'),
        ),
        migrations.AddField(
            model_name='gstr9',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tdsreport',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.client'),
        ),
        migrations.AddField(
            model_name='tdsreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
