# Generated by Django 5.2.4 on 2025-08-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0036_gdprrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gdprrequest',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='gdprrequest',
            name='processed',
        ),
        migrations.AddField(
            model_name='gdprrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='gdprrequest',
            name='request_type',
            field=models.CharField(choices=[('delete', 'Delete Account'), ('export', 'Export Data')], max_length=20),
        ),
    ]
