# Generated by Django 5.2.4 on 2025-08-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0038_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
