# Generated by Django 5.2.4 on 2025-08-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0041_brandingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingsettings',
            name='logo',
            field=models.ImageField(upload_to='branding/logos/'),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='primary_color',
            field=models.CharField(default='#007bff', help_text='Hex color like #007bff', max_length=7),
        ),
    ]
