# Generated by Django 5.2.4 on 2025-08-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0042_alter_brandingsettings_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatifscenario',
            name='scenario_type',
            field=models.CharField(choices=[('revenue', 'Revenue Increase'), ('expense', 'Expense Reduction'), ('custom', 'Custom or Strategic Scenarios'), ('project', 'Project-Based Scenarios')], max_length=20),
        ),
    ]
