# Generated by Django 5.2.4 on 2025-08-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0045_alter_message_options_message_is_read_message_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorpayment',
            name='filing_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
