# Generated by Django 4.2.23 on 2025-08-18 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0052_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingsettings',
            name='admin_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
