# Generated by Django 4.2.23 on 2025-08-20 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0053_alter_brandingsettings_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='receivable_account',
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivable_account', to='accounting_app.client'),
        ),
    ]
