# Generated by Django 4.2.23 on 2025-08-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0054_remove_client_receivable_account_account_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrecord',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
