# Generated by Django 4.2.23 on 2025-08-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0055_alter_taxrecord_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
