# Generated by Django 4.2.23 on 2025-08-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0056_useractivitylog_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivitylog',
            old_name='username',
            new_name='attempted_username',
        ),
    ]
