# Generated by Django 4.2.23 on 2025-08-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0057_rename_username_useractivitylog_attempted_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingmilestone',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cashflowprojection',
            name='description',
            field=models.CharField(blank=True, max_length=190),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientcontract',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='controltask',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='credit',
            name='reason',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='deal',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='path',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='description',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='purchaserequisitionline',
            name='description',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='quote',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(default='Quote for Deal', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='description',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='gst_portal_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tdsrecord',
            name='payee_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tdsrecord',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='description',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='attempted_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='description',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
