# Generated by Django 4.2.23 on 2025-08-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0058_alter_billingmilestone_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='title',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='description',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whatifscenario',
            name='name',
            field=models.CharField(max_length=190),
        ),
    ]
