# Generated by Django 4.2.23 on 2025-08-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0059_alter_approvalrequest_title_alter_fixedasset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=191, unique=True),
        ),
    ]
