# Generated by Django 4.2.23 on 2025-08-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0062_user_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Superuser', 'Superuser'), ('Accountant', 'Accountant'), ('Staff', 'Staff'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
    ]
