# Generated by Django 4.2.23 on 2025-08-28 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0064_projectstage'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalitem',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_app.projectstage'),
        ),
    ]
