# Generated by Django 4.2.23 on 2025-08-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0065_journalitem_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatifscenario',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='whatifscenario',
            name='created_at',
        ),
        migrations.AddField(
            model_name='whatifscenario',
            name='absolute_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='whatifscenario',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='whatifscenario',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='whatifscenario',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='whatifscenario',
            name='percentage_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='whatifscenario',
            name='scenario_type',
            field=models.CharField(choices=[('pct', 'Percentage change'), ('abs', 'Absolute change'), ('mult', 'Multiplier')], default='pct', max_length=8),
        ),
    ]
