# Generated by Django 4.2.23 on 2025-08-30 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0066_remove_whatifscenario_cost_center_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatifscenario',
            name='absolute_change',
        ),
        migrations.RemoveField(
            model_name='whatifscenario',
            name='multiplier',
        ),
        migrations.AddField(
            model_name='whatifscenario',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_app.costcenter'),
        ),
        migrations.AddField(
            model_name='whatifscenario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatifscenario',
            name='name',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='whatifscenario',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='whatifscenario',
            name='percentage_change',
            field=models.DecimalField(decimal_places=2, default=0, help_text='e.g. 10 for +10%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='whatifscenario',
            name='scenario_type',
            field=models.CharField(choices=[('revenue', 'Revenue Increase'), ('expense', 'Expense Reduction'), ('custom', 'Custom or Strategic Scenarios'), ('project', 'Project-Based Scenarios')], max_length=20),
        ),
    ]
