# Generated by Django 4.2.23 on 2025-09-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0068_user_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
    ]
