# Generated by Django 4.2.23 on 2025-09-01 06:28
from django.db import migrations, models, connection

def drop_conflicting_indexes(apps, schema_editor):
    # Drop only if they exist, to avoid errors on re-run
    idx_names = {
        'accounting__project_055e28_idx',     # redundant composite index
        'uniq_stage_name_per_project',        # unique(project, name)
        'uniq_stage_order_per_project',       # unique(project, order)
    }
    with connection.cursor() as c:
        c.execute("SHOW INDEX FROM accounting_app_projectstage;")
        existing = {row[2] for row in c.fetchall()}  # Key_name column
        for name in (idx_names & existing):
            c.execute(f"ALTER TABLE accounting_app_projectstage DROP INDEX {name};")

class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0073_alter_project_options_project_created_by'),
    ]

    operations = [
        # make the migration idempotent
        migrations.RunPython(drop_conflicting_indexes, migrations.RunPython.noop),

        migrations.AlterModelOptions(
            name='projectstage',
            options={'ordering': ('order', 'id')},
        ),

        # DO NOT add the redundant AddIndex:
        # migrations.AddIndex(... 'accounting__project_055e28_idx' ...),

        # Recreate the two unique constraints (they will create their indices)
        migrations.AddConstraint(
            model_name='projectstage',
            constraint=models.UniqueConstraint(
                fields=('project', 'name'),
                name='uniq_stage_name_per_project',
            ),
        ),
        migrations.AddConstraint(
            model_name='projectstage',
            constraint=models.UniqueConstraint(
                fields=('project', 'order'),
                name='uniq_stage_order_per_project',
            ),
        ),
    ]
