# Generated by Django 4.2.23 on 2025-09-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0074_alter_projectstage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
