# Generated by Django 4.2.23 on 2025-09-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0075_alter_projectstage_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectstage',
            name='accounting__project_055e28_idx',
        ),
    ]
       
