# Generated by Django 4.2.23 on 2025-09-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0076_remove_projectstage_accounting__project_055e28_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectstage',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='projectstage',
            name='uniq_stage_name_per_project',
        ),
        migrations.RemoveConstraint(
            model_name='projectstage',
            name='uniq_stage_order_per_project',
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
