# Generated by Django 4.2.23 on 2025-09-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0077_alter_project_options_alter_projectstage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
    ]
