# Generated by Django 4.2.23 on 2025-09-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0078_remove_account_created_by_remove_client_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstage',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AddConstraint(
            model_name='projectstage',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_stage_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projectstage',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='uniq_stage_order_per_project'),
        ),
    ]
