# Generated by Django 4.2.23 on 2025-09-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0093_contractorpayment_created_by_contractorpayment_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tdsrecord',
            constraint=models.UniqueConstraint(fields=('source', 'reference_id'), name='unique_tds_source_ref'),
        ),
    ]
