# Generated by Django 4.2.23 on 2025-09-12 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0094_tdsrecord_unique_tds_source_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdsrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tdsrecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_tds', to=settings.AUTH_USER_MODEL),
        ),
    ]
