# Generated by Django 4.2.23 on 2025-09-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0097_taxrecord_created_by_taxrecord_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrecord',
            name='invoice_number',
            field=models.CharField(max_length=100),
        ),
    ]
