# Generated by Django 4.2.23 on 2025-09-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0098_alter_taxrecord_invoice_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taxrecord',
            constraint=models.UniqueConstraint(fields=('invoice_number', 'owner'), name='unique_invoice_per_owner'),
        ),
    ]
