# Generated by Django 4.2.23 on 2025-09-15 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0099_taxrecord_unique_invoice_per_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_controltask', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controltaskinstance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_controlinstance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controltaskinstance',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_controlinstance', to=settings.AUTH_USER_MODEL),
        ),
    ]
