# Generated by Django 4.2.23 on 2025-09-15 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0102_exchangerate_created_by_exchangerate_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_costcenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_costcenter', to=settings.AUTH_USER_MODEL),
        ),
    ]
