# Generated by Django 4.2.23 on 2025-09-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0103_costcenter_created_by_costcenter_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
