# Generated by Django 4.2.23 on 2025-09-15 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0104_alter_costcenter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercompanytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intercompanytransaction',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_inter', to=settings.AUTH_USER_MODEL),
        ),
    ]
