# Generated by Django 4.2.23 on 2025-09-15 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0108_subscription_created_by_subscription_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptioninvoice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_subscriptioninvoice', to=settings.AUTH_USER_MODEL),
        ),
    ]
