# Generated by Django 4.2.23 on 2025-09-16 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0110_budget_created_by_budget_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forecast', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forecast',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_forecast', to=settings.AUTH_USER_MODEL),
        ),
    ]
