# Generated by Django 4.2.23 on 2025-09-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0113_cashflowprojection_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='initial_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
