# Generated by Django 4.2.23 on 2025-09-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0114_project_initial_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='initial_budget',
        ),
    ]
