# Generated by Django 4.2.23 on 2025-09-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0115_remove_project_initial_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatifscenario',
            name='target_month',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=9),
        ),
        migrations.AddField(
            model_name='whatifscenario',
            name='target_year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
