# Generated by Django 4.2.23 on 2025-09-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0116_whatifscenario_target_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatifscenario',
            name='target_month',
        ),
        migrations.RemoveField(
            model_name='whatifscenario',
            name='target_year',
        ),
    ]
