# Generated by Django 4.2.23 on 2025-09-17 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0119_product_created_by_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchaserequistion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_purchaserequistion', to=settings.AUTH_USER_MODEL),
        ),
    ]
