# Generated by Django 4.2.23 on 2025-09-17 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0121_purchaseorder_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchaserorderline', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_purchaseorderline', to=settings.AUTH_USER_MODEL),
        ),
    ]
