# Generated by Django 4.2.23 on 2025-09-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0122_purchaseorderline_created_by_purchaseorderline_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
