# Generated by Django 4.2.23 on 2025-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0123_alter_purchaseorder_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
