# Generated by Django 4.2.23 on 2025-09-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0124_alter_product_sku_alter_purchaserequisition_number'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaserequisition',
            constraint=models.UniqueConstraint(fields=('owner', 'number'), name='unique_pr_number_per_owner'),
        ),
    ]
