# Generated by Django 4.2.23 on 2025-09-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0125_purchaserequisition_unique_pr_number_per_owner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('owner', 'number'), name='unique_po_number_per_owner'),
        ),
    ]
