# Generated by Django 4.2.23 on 2025-09-17 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0128_vendorbill_created_by_vendorbill_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbillline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendorbillline', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorbillline',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_vendorbillline', to=settings.AUTH_USER_MODEL),
        ),
    ]
