# Generated by Django 4.2.23 on 2025-09-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0130_goodsreceiptline_created_by_goodsreceiptline_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceipt',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
