# Generated by Django 4.2.23 on 2025-09-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0131_alter_goodsreceipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbill',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
