# Generated by Django 4.2.23 on 2025-09-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0133_fixedasset_created_by_fixedasset_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_tag',
            field=models.CharField(max_length=50),
        ),
    ]
