# Generated by Django 4.2.23 on 2025-09-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0136_billingmilestone_created_by_billingmilestone_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_app.client'),
        ),
    ]
