# Generated by Django 4.2.23 on 2025-09-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0137_deal_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='crm_client',
        ),
    ]
