# Generated by Django 4.2.23 on 2025-09-20 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0140_brandingsettings_created_by_brandingsettings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdprrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gdpr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gdprrequest',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_gdpr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gstr3b',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gstr3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gstr3b',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_gstr3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_useractivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_useractivity', to=settings.AUTH_USER_MODEL),
        ),
    ]
