# Generated by Django 4.2.23 on 2025-11-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0144_profile_created_by_profile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_backgrounds/'),
        ),
    ]
